### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by ttfnrob** [zooniverse/Penguins#43]
- [x] www.penguinwatch.org works and you can classify [ @brian-c and @camallen ]
- [x] Site classifications submit and store as anticipated [ @camallen ]
- [x] Twitter, Facebook and G+ pages are ready and people have access [ @mrniaboc ]
- [x] The blog is working and first posts are scheduled [ @mrniaboc ]
- [x] Redirect blog.penguinwatch.org to Penguin Lifelines blog [ @astopy @aliburchard ]
- [x] Zooniverse home assets have been created [ @heathv @ttfnrob ]
- [x] There is a newsletter plan in place [ @mrniaboc ]
- [x] Milkman data is setup to be sent to correct Mongo DB [ @astopy @ttfnrob ]
- [x] Press release is out and contacts [ @ttfnrob @caitlinblack @penguintom79 ] are ready
- [x] Short list of talking points have been circulated to list [ @aliburchard ]
- [x] Status page URL is sent to science team [ @aliburchard ]
- [x] Final warning to dev@zooniverse.org list that Penguins is launching [ @aliburchard ]
